
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Mar 06 14:21:23 EST 2012
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUS = 4;
  public static final int DIVIDE = 6;
  public static final int NUMBER = 9;
  public static final int SEMI = 2;
  public static final int EOF = 0;
  public static final int PLUS = 3;
  public static final int ID = 10;
  public static final int error = 1;
  public static final int RPAREN = 8;
  public static final int TIMES = 5;
  public static final int LPAREN = 7;
}

