
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Mar 08 17:22:03 EST 2012
//----------------------------------------------------

package parse;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IP = 4;
  public static final int SET_HOST = 10;
  public static final int PROTOCOL = 12;
  public static final int SET_PROTO = 8;
  public static final int SET_SRC = 13;
  public static final int RECV = 17;
  public static final int UDP = 20;
  public static final int REGEXP = 3;
  public static final int STRING = 2;
  public static final int TCP = 19;
  public static final int EOF = 0;
  public static final int SET_NAME = 11;
  public static final int ANY = 21;
  public static final int SEND = 18;
  public static final int TCP_STREAM = 7;
  public static final int error = 1;
  public static final int PORT = 5;
  public static final int SET_TYPE = 9;
  public static final int SET_IP = 15;
  public static final int NLINE = 16;
  public static final int SET_DST = 14;
  public static final int WITH_FLAGS = 6;
}

